spring:
  datasource:
    url: "jdbc:mariadb://127.0.0.1:3306/qna?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul"
    username: "test"
    password: "test1234!@#$"